version: '2'

services:
  app:
    image: node:12-alpine
    command: "tail -F /dev/null"
    working_dir: /app
    user: "node"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - REDIS=redis://redis
      - TARGET=https://www.hentaiheroes.com
      - PROTOCOL_PROXY=http
      - TZ=Europe/Paris
      - NODE_ENV=development
      - TYPEORM_CONNECTION=mysql
      - TYPEORM_HOST=db
      - TYPEORM_USERNAME=root
      - TYPEORM_PASSWORD=pass
      - TYPEORM_DATABASE=hh
      - TYPEORM_PORT=3306
      - TYPEORM_SYNCHRONIZE=true
      - TYPEORM_ENTITIES=src/entities/**/*.ts
      - TYPEORM_LOGGING=error
      - VAPID_MAIL=postmaster@hentailheroesplus.com
      - VAPID_PUBLIC_KEY=BOJTObQRR1EPF8-1FWxZx1pNMIPqa8QM5Lq6cXpwr31PGoP_X5nmO_QdnWJAXkGtOneXmU6owPajYC9XsJ4l7eE
      - VAPID_PRIVATE_KEY=qb5OQV831KbtT6Pcb-2B9LFRbMpToK3FV-WxCTK8dP8
    depends_on:
      - redis
      - db
    links:
      - redis
      - db
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    networks:
      - app-net

  redis:
    image: redis:5-alpine
    logging:
      driver: "none"
    networks:
      - app-net

  db:
    image: mariadb:10
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=pass
    logging:
      driver: "none"
    networks:
      - app-net

networks:
  app-net:
